kind: Service
apiVersion: v1
metadata:
  name: csi-snapshotter
  labels:
    app: csi-snapshotter
spec:
  selector:
    app: csi-snapshotter
  ports:
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-snapshotter
spec:
  replicas: 3
  selector:
    matchLabels:
      external-provisioner: csi-snapshotter
  template:
    metadata:
      labels:
        external-provisioner: csi-snapshotter
    spec:
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v2.0.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--enable-leader-election"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-nfs
          image: gozap/csi-nfs:debug
          args:
            - "--"
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nfsserver=$(NFS_SERVER)"
            - "--nfssharepoint=$(NFS_SHARE)"
            - "--nfslocalmountpoint=$(NFS_LOCAL_MOUNT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NFS_SERVER
              value: 172.16.10.50
            - name: NFS_SHARE
              value: /mnt/freenas/kubernetes
            - name: NFS_LOCAL_MOUNT
              value: /nfs
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: nfs-server
              mountPath: /nfs

      volumes:
        - name: socket-dir
          emptyDir:
        - name: nfs-server
          nfs:
            server: 172.16.10.50
            path: /mnt/freenas/kubernetes

