# This YAML file demonstrates how to deploy the external
# provisioner for use with the mock CSI driver. It
# depends on the RBAC definitions from rbac.yaml.

kind: Service
apiVersion: v1
metadata:
  name: csi-attacher
  labels:
    app: csi-attacher
spec:
  selector:
    app: csi-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-attacher
spec:
  replicas: 3
  selector:
    matchLabels:
      external-attacher: csi-attacher
  template:
    metadata:
      labels:
        external-attacher: csi-attacher
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/csi-nfsplugin/csi.socket
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/csi-nfsplugin/
        - name: socket2tcp
          image: mritd/socket2tcp:v1.0.0
          args:
            - "--socket=$(CSI_ENDPOINT)"
            - "--remote=$(FORWARD_ENDPOINT)"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: CSI_ENDPOINT
              value: /var/lib/csi/sockets/csi-nfsplugin/csi.socket
            - name: FORWARD_ENDPOINT
              value: 10.24.0.2:8080
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/csi-nfsplugin/

      volumes:
        - name: socket-dir
          emptyDir:

