# This YAML file contains driver-registrar & csi driver nodeplugin API objects
# that are necessary to run CSI nodeplugin for nfs
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-driver-registrar
spec:
  selector:
    matchLabels:
      app: csi-driver-registrar
  template:
    metadata:
      labels:
        app: csi-driver-registrar
    spec:
      hostNetwork: true
      containers:
        - name: csi-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi-nfsplugin/csi.sock"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
#        - name: nfs
#          securityContext:
#            privileged: true
#            capabilities:
#              add: ["SYS_ADMIN"]
#            allowPrivilegeEscalation: true
#          image: gozap/csi-node-driver-registrar
#          args :
#            - "--nodeid=$(NODE_ID)"
#            - "--endpoint=unix:///csi/csi.sock"
#          env:
#            - name: NODE_ID
#              valueFrom:
#                fieldRef:
#                  fieldPath: spec.nodeName
#          imagePullPolicy: IfNotPresent
#          volumeMounts:
#            - name: plugin-dir
#              mountPath: /csi
#            - name: pods-mount-dir
#              mountPath: /var/lib/kubelet/pods
#              mountPropagation: Bidirectional
        - name: socket2tcp
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: mritd/socket2tcp:v1.0.0
          args :
            - "--socket=$(CSI_ENDPOINT)"
            - "--remote=$(FORWARD_ENDPOINT)"
          lifecycle:
            preStop:
              exec:
                command: ["bash","-c","rm -rf /registration/csi-nfsplugin /registration/csi-nfsplugin-reg.sock"]
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: FORWARD_ENDPOINT
              value: 10.10.2.22:9000
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-nfsplugin
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory

