# This YAML file demonstrates how to deploy the external
# provisioner for use with the mock CSI driver. It
# depends on the RBAC definitions from rbac.yaml.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-provisioner
spec:
  replicas: 3
  selector:
    matchLabels:
      external-provisioner: csi-provisioner
  template:
    metadata:
      labels:
        external-provisioner: csi-provisioner
    spec:
      # debug only(connect to dlv 2345 port)
      #hostNetwork: true
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ENDPOINT)"
            - "--enable-leader-election"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-nfs
          image: gozap/csi-nfs:v1.0.0
          args:
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nfsserver=$(NFS_SERVER)"
            - "--nfssharepoint=$(NFS_SHARE)"
            - "--nfslocalmountpoint=$(NFS_LOCAL_MOUNT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NFS_LOCAL_MOUNT
              value: /nfs
            # replace with real nfs server config
            - name: NFS_SERVER
              value: 172.16.10.50
            - name: NFS_SHARE
              value: /mnt/freenas/kubernetes
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: nfs-server
              mountPath: /nfs

      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: nfs-server
          nfs:
            # replace with real nfs server config
            server: 172.16.10.50
            path: /mnt/freenas/kubernetes

